apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kuma-demo-mesh-resource
  namespace: flux-system
spec:
  path: ./infrastructure/dev/kuma-mesh-policies
  interval: 10m
  retryInterval: 1m
  prune: true
  dependsOn:
    - name: kuma
  sourceRef:
    kind: GitRepository
    name: flux-system