apiVersion: v1
kind: Namespace
metadata:
  name: fleet-api-demo
  labels:
    kuma.io/sidecar-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-api
  namespace: fleet-api-demo
  labels:
    app: fleet-api
    kuma.io/sidecar-injection: enabled
spec:
  replicas: 3
  selector:
    matchLabels:
      service: fleet-api
  template:
    metadata:
      labels:
        app: fleet-api
        service: fleet-api
    spec:
      containers:
        - name: fleet-api
          image: arunvambur/fleet-api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCOR_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: fleet-api
  namespace: fleet-api-demo
  labels:
    app: fleet-api
    service: fleet-api
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    service: fleet-api