apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kuma
  namespace: kuma-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kuma
      version: '1.8.0'
      sourceRef:
        kind: HelmRepository
        name: kuma
        namespace: flux-system
      interval: 1m