apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kuma-mesh
  namespace: kuma-mesh-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kuma-system
      version: '1.7.x'
      sourceRef:
        kind: HelmRepository
        name: kuma-mesh
        namespace: kuma-mesh-system
      interval: 1m
      values:
        
  values:
    replicaCount: 1  