apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kuma
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kuma
      version: '1.7.x'
      sourceRef:
        kind: HelmRepository
        name: kuma
        namespace: flux-system
      interval: 1m